%Doctor.Config{
  min_overall_spec_coverage: 0,
  min_overall_moduledoc_coverage: 95,
  struct_type_spec_required: false,
  ignore_modules: [
    Agentic.AgentProtocol,
    Agentic.AgentProtocol.CLI,
    Agentic.ModelRouter.Free.Route,
    Agentic.Protocol.Error.NotFound,
    Agentic.Protocol.Error.Unavailable,
    Agentic.Protocol.Error.SessionError,
    Agentic.Storage.Context,
    Agentic.Subagent.Coordinator,
    Agentic.Tools,
    Agentic.Tools.Gateway,
    Agentic.Tools.Memory,
    Agentic.Tools.Skill,
    # Macro module — its `__using__/1` body expands into the
    # per-agent provider wrappers (Cursor, Gemini, etc.). The
    # generated functions live there, so doctor sees CodingAgentBase
    # as having no implementations. The wrappers carry the docs.
    Agentic.LLM.Provider.CodingAgentBase,
    # Submodules generated by `use Cldr` in lib/agentic/cldr.ex.
    # We don't control their docstrings.
    Agentic.Cldr.Number.System,
    Agentic.Cldr.Number.Symbol,
    Agentic.Cldr.Number.Formatter.Decimal,
    Agentic.Cldr.Currency,
    Agentic.Cldr.Rbnf.Spellout,
    Agentic.Cldr.Rbnf.Ordinal,
    Agentic.Cldr.Rbnf.NumberSystem,
    Agentic.Cldr.Number.Transliterate,
    Agentic.Cldr.Number.PluralRule.Range,
    Agentic.Cldr.Number.Ordinal,
    Agentic.Cldr.Number.Format,
    Agentic.Cldr.Number.Cardinal,
    Agentic.Cldr.Number,
    Agentic.Cldr.Money,
    Agentic.Cldr.Locale,
    Agentic.Cldr.AcceptLanguage,
    # Internal struct used by SpendTracker — documented as part of
    # the parent module.
    Agentic.LLM.SpendTracker.Window
  ]
}
